### ISSUE TITLE
Getting various python syntax errors.

### ISSUE THREAD

**Issue by andremalenfant** [Anonoei/klipper_auto_tap#13]
I am getting various syntax errors. Is this built to run with Python 3?

First one that comes:

Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 121, in load_object
    mod = importlib.import_module('extras.' + module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/klipper/klippy/extras/auto_tap.py", line 15
    def Calculate(self, travel: float):

**Comment by andremalenfant** [comment]
disregard that, upgraded to python 3
